export interface EmojiEntry {
  emoji: string;
  keywords: string[];
}

export interface EmojiCategory {
  name: string;
  icon: string;
  emojis: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: "Smileys & Emotion",
    icon: "😀",
    emojis: [
      { emoji: "😀", keywords: ["grin", "happy", "smile"] },
      { emoji: "😃", keywords: ["smile", "happy", "joy"] },
      { emoji: "😄", keywords: ["laugh", "happy", "smile"] },
      { emoji: "😁", keywords: ["grin", "beam", "happy"] },
      { emoji: "😆", keywords: ["laugh", "satisfied", "grin"] },
      { emoji: "😅", keywords: ["sweat", "nervous", "laugh"] },
      { emoji: "🤣", keywords: ["rofl", "laugh", "rolling"] },
      { emoji: "😂", keywords: ["joy", "tears", "laugh"] },
      { emoji: "🙂", keywords: ["smile", "slight", "okay"] },
      { emoji: "😊", keywords: ["blush", "smile", "happy"] },
      { emoji: "😇", keywords: ["angel", "halo", "innocent"] },
      { emoji: "🥰", keywords: ["love", "hearts", "adore"] },
      { emoji: "😍", keywords: ["heart eyes", "love", "crush"] },
      { emoji: "🤩", keywords: ["star eyes", "excited", "wow"] },
      { emoji: "😘", keywords: ["kiss", "love", "blow kiss"] },
      { emoji: "😗", keywords: ["kiss", "whistle", "lips"] },
      { emoji: "😚", keywords: ["kiss", "blush", "affection"] },
      { emoji: "😋", keywords: ["yum", "delicious", "tongue"] },
      { emoji: "😛", keywords: ["tongue", "playful", "silly"] },
      { emoji: "😜", keywords: ["wink", "tongue", "silly"] },
      { emoji: "🤪", keywords: ["zany", "crazy", "wild"] },
      { emoji: "😝", keywords: ["tongue", "squint", "taste"] },
      { emoji: "🤑", keywords: ["money", "rich", "dollar"] },
      { emoji: "🤗", keywords: ["hug", "warm", "embrace"] },
      { emoji: "🤭", keywords: ["giggle", "cover", "oops"] },
      { emoji: "🤫", keywords: ["shush", "quiet", "secret"] },
      { emoji: "🤔", keywords: ["think", "hmm", "wonder"] },
      { emoji: "😐", keywords: ["neutral", "blank", "meh"] },
      { emoji: "😑", keywords: ["expressionless", "blank", "unamused"] },
      { emoji: "😶", keywords: ["silent", "mute", "speechless"] },
      { emoji: "🙄", keywords: ["eye roll", "annoyed", "whatever"] },
      { emoji: "😏", keywords: ["smirk", "smug", "flirt"] },
      { emoji: "😣", keywords: ["persevere", "struggle", "frustrated"] },
      { emoji: "😥", keywords: ["sad", "relieved", "disappointed"] },
      { emoji: "😮", keywords: ["open mouth", "surprised", "wow"] },
      { emoji: "🤐", keywords: ["zipper", "sealed", "quiet"] },
      { emoji: "😯", keywords: ["hushed", "stunned", "surprised"] },
      { emoji: "😪", keywords: ["sleepy", "tired", "snot bubble"] },
      { emoji: "😫", keywords: ["tired", "weary", "exhausted"] },
      { emoji: "🥱", keywords: ["yawn", "bored", "sleepy"] },
      { emoji: "😴", keywords: ["sleep", "zzz", "nap"] },
    ],
  },
  {
    name: "People & Gestures",
    icon: "👋",
    emojis: [
      { emoji: "👋", keywords: ["wave", "hello", "bye"] },
      { emoji: "🤚", keywords: ["raised hand", "stop", "back"] },
      { emoji: "🖐", keywords: ["hand", "fingers", "five"] },
      { emoji: "✋", keywords: ["hand", "stop", "high five"] },
      { emoji: "🖖", keywords: ["vulcan", "spock", "trek"] },
      { emoji: "👌", keywords: ["ok", "perfect", "fine"] },
      { emoji: "🤌", keywords: ["pinched", "italian", "chef"] },
      { emoji: "🤏", keywords: ["pinch", "small", "tiny"] },
      { emoji: "✌", keywords: ["peace", "victory", "two"] },
      { emoji: "🤞", keywords: ["crossed fingers", "luck", "hope"] },
      { emoji: "🤟", keywords: ["love you", "rock", "sign"] },
      { emoji: "🤘", keywords: ["rock on", "metal", "horns"] },
      { emoji: "🤙", keywords: ["call me", "shaka", "hang loose"] },
      { emoji: "👈", keywords: ["left", "point", "direction"] },
      { emoji: "👉", keywords: ["right", "point", "direction"] },
      { emoji: "👆", keywords: ["up", "point", "above"] },
      { emoji: "🖕", keywords: ["middle finger", "rude", "flip off"] },
      { emoji: "👇", keywords: ["down", "point", "below"] },
      { emoji: "☝", keywords: ["up", "index", "one"] },
      { emoji: "👍", keywords: ["thumbs up", "yes", "approve"] },
      { emoji: "👎", keywords: ["thumbs down", "no", "dislike"] },
      { emoji: "✊", keywords: ["fist", "power", "punch"] },
      { emoji: "👊", keywords: ["fist bump", "punch", "bro"] },
      { emoji: "🤛", keywords: ["left fist", "bump", "punch"] },
      { emoji: "🤜", keywords: ["right fist", "bump", "punch"] },
      { emoji: "👏", keywords: ["clap", "applause", "bravo"] },
      { emoji: "🙌", keywords: ["raise", "celebrate", "hooray"] },
      { emoji: "👐", keywords: ["open hands", "jazz", "spread"] },
      { emoji: "🤲", keywords: ["palms up", "prayer", "cupped"] },
      { emoji: "🤝", keywords: ["handshake", "deal", "agree"] },
      { emoji: "🙏", keywords: ["pray", "please", "thanks"] },
    ],
  },
  {
    name: "Animals & Nature",
    icon: "🐶",
    emojis: [
      { emoji: "🐶", keywords: ["dog", "puppy", "pet"] },
      { emoji: "🐱", keywords: ["cat", "kitten", "pet"] },
      { emoji: "🐭", keywords: ["mouse", "rodent", "small"] },
      { emoji: "🐹", keywords: ["hamster", "pet", "cute"] },
      { emoji: "🐰", keywords: ["rabbit", "bunny", "easter"] },
      { emoji: "🦊", keywords: ["fox", "clever", "red"] },
      { emoji: "🐻", keywords: ["bear", "teddy", "animal"] },
      { emoji: "🐼", keywords: ["panda", "bear", "bamboo"] },
      { emoji: "🐨", keywords: ["koala", "australia", "cute"] },
      { emoji: "🐯", keywords: ["tiger", "cat", "stripes"] },
      { emoji: "🦁", keywords: ["lion", "king", "mane"] },
      { emoji: "🐮", keywords: ["cow", "moo", "farm"] },
      { emoji: "🐷", keywords: ["pig", "oink", "farm"] },
      { emoji: "🐸", keywords: ["frog", "toad", "ribbit"] },
      { emoji: "🐵", keywords: ["monkey", "ape", "primate"] },
      { emoji: "🐔", keywords: ["chicken", "rooster", "farm"] },
      { emoji: "🐧", keywords: ["penguin", "ice", "arctic"] },
      { emoji: "🐦", keywords: ["bird", "tweet", "fly"] },
      { emoji: "🦆", keywords: ["duck", "quack", "pond"] },
      { emoji: "🦅", keywords: ["eagle", "bird", "freedom"] },
      { emoji: "🦉", keywords: ["owl", "wise", "night"] },
      { emoji: "🐺", keywords: ["wolf", "howl", "wild"] },
      { emoji: "🐗", keywords: ["boar", "pig", "wild"] },
      { emoji: "🐴", keywords: ["horse", "pony", "ride"] },
      { emoji: "🦄", keywords: ["unicorn", "magic", "fantasy"] },
      { emoji: "🐝", keywords: ["bee", "honey", "buzz"] },
      { emoji: "🐛", keywords: ["bug", "insect", "caterpillar"] },
      { emoji: "🦋", keywords: ["butterfly", "insect", "pretty"] },
      { emoji: "🐌", keywords: ["snail", "slow", "shell"] },
      { emoji: "🐞", keywords: ["ladybug", "insect", "luck"] },
    ],
  },
  {
    name: "Food & Drink",
    icon: "🍎",
    emojis: [
      { emoji: "🍎", keywords: ["apple", "red", "fruit"] },
      { emoji: "🍐", keywords: ["pear", "fruit", "green"] },
      { emoji: "🍊", keywords: ["orange", "citrus", "fruit"] },
      { emoji: "🍋", keywords: ["lemon", "citrus", "sour"] },
      { emoji: "🍌", keywords: ["banana", "fruit", "yellow"] },
      { emoji: "🍉", keywords: ["watermelon", "summer", "fruit"] },
      { emoji: "🍇", keywords: ["grapes", "wine", "fruit"] },
      { emoji: "🍓", keywords: ["strawberry", "berry", "fruit"] },
      { emoji: "🫐", keywords: ["blueberry", "berry", "fruit"] },
      { emoji: "🍈", keywords: ["melon", "fruit", "cantaloupe"] },
      { emoji: "🍒", keywords: ["cherry", "fruit", "red"] },
      { emoji: "🍑", keywords: ["peach", "fruit", "fuzzy"] },
      { emoji: "🥭", keywords: ["mango", "fruit", "tropical"] },
      { emoji: "🍍", keywords: ["pineapple", "fruit", "tropical"] },
      { emoji: "🥥", keywords: ["coconut", "tropical", "palm"] },
      { emoji: "🥝", keywords: ["kiwi", "fruit", "green"] },
      { emoji: "🍅", keywords: ["tomato", "vegetable", "red"] },
      { emoji: "🥑", keywords: ["avocado", "guacamole", "green"] },
      { emoji: "🍆", keywords: ["eggplant", "aubergine", "purple"] },
      { emoji: "🥦", keywords: ["broccoli", "vegetable", "green"] },
      { emoji: "🥬", keywords: ["leafy green", "lettuce", "salad"] },
      { emoji: "🥒", keywords: ["cucumber", "pickle", "vegetable"] },
      { emoji: "🌶", keywords: ["pepper", "hot", "spicy"] },
      { emoji: "🫑", keywords: ["bell pepper", "vegetable", "green"] },
      { emoji: "🌽", keywords: ["corn", "maize", "cob"] },
      { emoji: "🥕", keywords: ["carrot", "vegetable", "orange"] },
      { emoji: "🧄", keywords: ["garlic", "clove", "flavor"] },
      { emoji: "🧅", keywords: ["onion", "vegetable", "cry"] },
      { emoji: "🥔", keywords: ["potato", "spud", "vegetable"] },
      { emoji: "🍞", keywords: ["bread", "loaf", "toast"] },
      { emoji: "🥐", keywords: ["croissant", "pastry", "french"] },
      { emoji: "🥖", keywords: ["baguette", "bread", "french"] },
    ],
  },
  {
    name: "Travel & Places",
    icon: "🚗",
    emojis: [
      { emoji: "🚗", keywords: ["car", "drive", "vehicle"] },
      { emoji: "🚕", keywords: ["taxi", "cab", "ride"] },
      { emoji: "🚙", keywords: ["suv", "car", "vehicle"] },
      { emoji: "🚌", keywords: ["bus", "transit", "public"] },
      { emoji: "🚎", keywords: ["trolleybus", "transit", "electric"] },
      { emoji: "🏎", keywords: ["race car", "fast", "speed"] },
      { emoji: "🚓", keywords: ["police", "cop", "car"] },
      { emoji: "🚑", keywords: ["ambulance", "emergency", "hospital"] },
      { emoji: "🚒", keywords: ["fire truck", "emergency", "firefighter"] },
      { emoji: "🚐", keywords: ["minibus", "van", "shuttle"] },
      { emoji: "🛻", keywords: ["pickup", "truck", "haul"] },
      { emoji: "🚚", keywords: ["truck", "delivery", "moving"] },
      { emoji: "🚛", keywords: ["semi", "truck", "freight"] },
      { emoji: "🚜", keywords: ["tractor", "farm", "plow"] },
      { emoji: "✈", keywords: ["airplane", "fly", "travel"] },
      { emoji: "🛩", keywords: ["small plane", "aircraft", "fly"] },
      { emoji: "🚀", keywords: ["rocket", "space", "launch"] },
      { emoji: "🛸", keywords: ["ufo", "alien", "flying saucer"] },
      { emoji: "🚁", keywords: ["helicopter", "chopper", "fly"] },
      { emoji: "🛶", keywords: ["canoe", "paddle", "boat"] },
      { emoji: "⛵", keywords: ["sailboat", "boat", "wind"] },
      { emoji: "🚤", keywords: ["speedboat", "boat", "fast"] },
      { emoji: "🛥", keywords: ["motorboat", "boat", "yacht"] },
      { emoji: "🛳", keywords: ["cruise", "ship", "ocean"] },
      { emoji: "⛴", keywords: ["ferry", "boat", "ship"] },
      { emoji: "🚢", keywords: ["ship", "boat", "ocean"] },
      { emoji: "🏠", keywords: ["house", "home", "building"] },
      { emoji: "🏡", keywords: ["house", "garden", "home"] },
      { emoji: "🏢", keywords: ["office", "building", "work"] },
      { emoji: "🏣", keywords: ["post office", "mail", "japan"] },
      { emoji: "🏥", keywords: ["hospital", "medical", "health"] },
      { emoji: "🏦", keywords: ["bank", "money", "finance"] },
    ],
  },
  {
    name: "Activities",
    icon: "⚽",
    emojis: [
      { emoji: "⚽", keywords: ["soccer", "football", "ball"] },
      { emoji: "🏀", keywords: ["basketball", "ball", "sport"] },
      { emoji: "🏈", keywords: ["football", "american", "nfl"] },
      { emoji: "⚾", keywords: ["baseball", "ball", "sport"] },
      { emoji: "🥎", keywords: ["softball", "ball", "sport"] },
      { emoji: "🎾", keywords: ["tennis", "ball", "racket"] },
      { emoji: "🏐", keywords: ["volleyball", "ball", "sport"] },
      { emoji: "🏉", keywords: ["rugby", "ball", "sport"] },
      { emoji: "🥏", keywords: ["frisbee", "disc", "throw"] },
      { emoji: "🎱", keywords: ["pool", "billiards", "eight ball"] },
      { emoji: "🏓", keywords: ["ping pong", "table tennis", "paddle"] },
      { emoji: "🏸", keywords: ["badminton", "shuttlecock", "racket"] },
      { emoji: "🏒", keywords: ["hockey", "ice", "stick"] },
      { emoji: "🥅", keywords: ["goal", "net", "score"] },
      { emoji: "⛳", keywords: ["golf", "hole", "flag"] },
      { emoji: "🏹", keywords: ["archery", "bow", "arrow"] },
      { emoji: "🎣", keywords: ["fishing", "rod", "catch"] },
      { emoji: "🤿", keywords: ["diving", "snorkel", "swim"] },
      { emoji: "🥊", keywords: ["boxing", "glove", "fight"] },
      { emoji: "🥋", keywords: ["martial arts", "karate", "judo"] },
      { emoji: "🎽", keywords: ["jersey", "running", "shirt"] },
      { emoji: "⛸", keywords: ["ice skating", "skate", "rink"] },
      { emoji: "🥌", keywords: ["curling", "stone", "ice"] },
      { emoji: "🛷", keywords: ["sled", "snow", "toboggan"] },
      { emoji: "🎿", keywords: ["ski", "snow", "winter"] },
      { emoji: "⛷", keywords: ["skier", "ski", "snow"] },
      { emoji: "🏂", keywords: ["snowboard", "snow", "winter"] },
      { emoji: "🏋", keywords: ["weightlifting", "gym", "strong"] },
      { emoji: "🤼", keywords: ["wrestling", "fight", "sport"] },
      { emoji: "🤸", keywords: ["cartwheel", "gymnastics", "flip"] },
      { emoji: "⛹", keywords: ["basketball player", "bounce", "dribble"] },
      { emoji: "🤺", keywords: ["fencing", "sword", "duel"] },
    ],
  },
  {
    name: "Objects",
    icon: "💻",
    emojis: [
      { emoji: "⌚", keywords: ["watch", "time", "wrist"] },
      { emoji: "📱", keywords: ["phone", "mobile", "cell"] },
      { emoji: "💻", keywords: ["laptop", "computer", "mac"] },
      { emoji: "⌨", keywords: ["keyboard", "type", "input"] },
      { emoji: "🖥", keywords: ["desktop", "computer", "monitor"] },
      { emoji: "🖨", keywords: ["printer", "print", "paper"] },
      { emoji: "🖱", keywords: ["mouse", "click", "cursor"] },
      { emoji: "🖲", keywords: ["trackball", "input", "control"] },
      { emoji: "🕹", keywords: ["joystick", "game", "arcade"] },
      { emoji: "🗜", keywords: ["clamp", "compress", "vice"] },
      { emoji: "💽", keywords: ["minidisc", "disk", "data"] },
      { emoji: "💾", keywords: ["floppy", "save", "disk"] },
      { emoji: "💿", keywords: ["cd", "disc", "music"] },
      { emoji: "📀", keywords: ["dvd", "disc", "movie"] },
      { emoji: "📷", keywords: ["camera", "photo", "picture"] },
      { emoji: "📸", keywords: ["camera flash", "photo", "snap"] },
      { emoji: "📹", keywords: ["video camera", "record", "film"] },
      { emoji: "🎥", keywords: ["movie camera", "film", "cinema"] },
      { emoji: "📽", keywords: ["projector", "film", "movie"] },
      { emoji: "🎞", keywords: ["film frames", "movie", "reel"] },
      { emoji: "📞", keywords: ["telephone", "call", "receiver"] },
      { emoji: "☎", keywords: ["phone", "telephone", "call"] },
      { emoji: "📟", keywords: ["pager", "beep", "retro"] },
      { emoji: "📠", keywords: ["fax", "machine", "office"] },
      { emoji: "📺", keywords: ["tv", "television", "screen"] },
      { emoji: "📻", keywords: ["radio", "music", "broadcast"] },
      { emoji: "🎙", keywords: ["microphone", "podcast", "studio"] },
      { emoji: "🎚", keywords: ["slider", "level", "volume"] },
      { emoji: "🎛", keywords: ["knobs", "control", "dial"] },
      { emoji: "🧭", keywords: ["compass", "navigate", "direction"] },
      { emoji: "⏱", keywords: ["stopwatch", "timer", "speed"] },
      { emoji: "⏲", keywords: ["timer", "clock", "countdown"] },
      { emoji: "⏰", keywords: ["alarm", "clock", "wake"] },
    ],
  },
  {
    name: "Symbols",
    icon: "❤",
    emojis: [
      { emoji: "❤", keywords: ["heart", "love", "red"] },
      { emoji: "🧡", keywords: ["heart", "orange", "love"] },
      { emoji: "💛", keywords: ["heart", "yellow", "love"] },
      { emoji: "💚", keywords: ["heart", "green", "love"] },
      { emoji: "💙", keywords: ["heart", "blue", "love"] },
      { emoji: "💜", keywords: ["heart", "purple", "love"] },
      { emoji: "🖤", keywords: ["heart", "black", "dark"] },
      { emoji: "🤍", keywords: ["heart", "white", "pure"] },
      { emoji: "🤎", keywords: ["heart", "brown", "love"] },
      { emoji: "💔", keywords: ["broken heart", "sad", "heartbreak"] },
      { emoji: "❣", keywords: ["heart exclamation", "love", "heavy"] },
      { emoji: "💕", keywords: ["two hearts", "love", "couple"] },
      { emoji: "💞", keywords: ["revolving hearts", "love", "romance"] },
      { emoji: "💟", keywords: ["heart decoration", "love", "ornament"] },
      { emoji: "❤️‍🔥", keywords: ["heart fire", "passion", "burning"] },
      { emoji: "💘", keywords: ["cupid", "arrow", "love"] },
      { emoji: "💝", keywords: ["gift heart", "ribbon", "love"] },
      { emoji: "💖", keywords: ["sparkling heart", "love", "shine"] },
      { emoji: "💗", keywords: ["growing heart", "love", "pulse"] },
      { emoji: "💓", keywords: ["beating heart", "love", "pulse"] },
      { emoji: "✨", keywords: ["sparkles", "magic", "shine"] },
      { emoji: "⭐", keywords: ["star", "gold", "favorite"] },
      { emoji: "🌟", keywords: ["glowing star", "bright", "shine"] },
      { emoji: "💫", keywords: ["dizzy", "star", "shooting"] },
      { emoji: "🔥", keywords: ["fire", "hot", "lit"] },
      { emoji: "💥", keywords: ["boom", "explosion", "bang"] },
      { emoji: "💢", keywords: ["anger", "mad", "symbol"] },
      { emoji: "💦", keywords: ["sweat", "water", "drops"] },
      { emoji: "💨", keywords: ["wind", "dash", "fast"] },
      { emoji: "🕊", keywords: ["dove", "peace", "bird"] },
      { emoji: "☮", keywords: ["peace", "symbol", "sign"] },
      { emoji: "✝", keywords: ["cross", "christian", "religion"] },
      { emoji: "☪", keywords: ["islam", "crescent", "moon"] },
      { emoji: "🕉", keywords: ["om", "hindu", "symbol"] },
      { emoji: "☸", keywords: ["dharma", "wheel", "buddhism"] },
    ],
  },
  {
    name: "Flags",
    icon: "🏁",
    emojis: [
      { emoji: "🏁", keywords: ["checkered", "race", "finish"] },
      { emoji: "🚩", keywords: ["red flag", "warning", "triangular"] },
      { emoji: "🎌", keywords: ["crossed flags", "japan", "celebration"] },
      { emoji: "🏴", keywords: ["black flag", "pirate", "dark"] },
      { emoji: "🏳", keywords: ["white flag", "surrender", "peace"] },
      { emoji: "🏳️‍🌈", keywords: ["rainbow", "pride", "lgbtq"] },
      { emoji: "🏳️‍⚧️", keywords: ["transgender", "trans", "pride"] },
      { emoji: "🇺🇸", keywords: ["usa", "america", "united states"] },
      { emoji: "🇬🇧", keywords: ["uk", "britain", "england"] },
      { emoji: "🇫🇷", keywords: ["france", "french", "paris"] },
      { emoji: "🇩🇪", keywords: ["germany", "german", "berlin"] },
      { emoji: "🇮🇹", keywords: ["italy", "italian", "rome"] },
      { emoji: "🇪🇸", keywords: ["spain", "spanish", "madrid"] },
      { emoji: "🇯🇵", keywords: ["japan", "japanese", "tokyo"] },
      { emoji: "🇰🇷", keywords: ["korea", "south korea", "seoul"] },
      { emoji: "🇨🇳", keywords: ["china", "chinese", "beijing"] },
      { emoji: "🇷🇺", keywords: ["russia", "russian", "moscow"] },
      { emoji: "🇧🇷", keywords: ["brazil", "brazilian", "brasilia"] },
      { emoji: "🇮🇳", keywords: ["india", "indian", "delhi"] },
      { emoji: "🇦🇺", keywords: ["australia", "aussie", "canberra"] },
      { emoji: "🇨🇦", keywords: ["canada", "canadian", "ottawa"] },
      { emoji: "🇲🇽", keywords: ["mexico", "mexican", "mexico city"] },
    ],
  },
];
